### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by owenshen24** [owenshen24/0xmons#1]
- [ ] Add claim page
- [ ] Add yfbeta pool
- [ ] Add LP staking pool
- [ ] Build staking UI for both pools
- [ ] Update home page to better explain the idea + images
- [ ] Add footer links to socials
- [ ] Update the 0xmons contracts, think more about that. (Maybe launch staking and the new 0xmons contract at the same time so people have an immediate use for the tokens.)

**Comment by TheDon12** [comment]
Coming along nicely :-) 
Great Owen.
